version: '3'

services:
  firebase:
    container_name: firebase-launcher
    build:
      context: .
    restart: unless-stopped
    environment:
      - UI_PORT=8800
      - AUTH_PORT=9099
      - STORAGE_PORT=9199
      - FIRESTORE_PORT=8082
      - SERVER_PORT=1000
      - AUTO_START=true
    ports:
      - 8800:8800 #ui
      - 9099:9099 #auth
      - 9199:9199 #storage
      - 8082:8082 #firestore
      - 1000:1000 #server