name: Deploy Container

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container
        if: '!cancelled()'
        run: |-
          docker build -t "ghcr.io/cbridges1/firebase-launcher:latest" ./
          docker push "ghcr.io/cbridges1/firebase-launcher:latest"